#!/bin/bash

OS_VERSION=3.10
OS=alpine-$OS_VERSION
ARCHES=(x86 x86_64 armhf aarch64)

for arch in ${ARCHES[@]}; do
    BUILD_ARGS=(
        --build-arg MESON_VERSION=$DOCKER_TAG
        --build-arg OS_VERSION=$OS_VERSION
        --build-arg OS_ARCH=$arch
    )
    IMAGE=$DOCKER_REPO:$DOCKER_TAG-gcc-$OS-$arch

    docker build ${BUILD_ARGS[@]} -t $IMAGE -f Dockerfile.gcc .
    docker tag $IMAGE $DOCKER_REPO:gcc-$OS-$arch
    docker tag $IMAGE $DOCKER_REPO:$OS-$arch

    IMAGE=$DOCKER_REPO:$DOCKER_TAG-llvm-$OS-$arch

    docker build ${BUILD_ARGS[@]} -t $IMAGE -f Dockerfile.llvm .
    docker tag $IMAGE $DOCKER_REPO:llvm-$OS-$arch
done
