ARG OS_ARCH
ARG OS_VERSION

FROM snaipe/alpine-qemu:${OS_ARCH}-${OS_VERSION}

ARG MESON_VERSION=0.51.2

RUN apk add --no-cache clang python3 python3-pip ninja git

RUN pip3 install meson==${MESON_VERSION}
